name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Generate documentation
        run: yarn docs

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs

      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
